version: 0.3

phases:
  pre_build:
    commands:
      - cd ./web/frontend && npm install && cd ../../
      - cd ./web/backend && cd ../../
  build:
    commands:
      - cd ./web/frontend && npm run build && npm run export && cd ../../
      - cd ./web/backend && cd ../../
  post_build:
    commands:
      - mv ./web/frontend/out ./build
      - mv ./web/backend ./backend
artifacts:
  secondary-artifacts:
    Frontend:
      files:
        - '**/*'
      base-directory: ./build
    Backend:
      files:
        - '**/*'
      base-directory: ./backend