version: 0.2

phases:
  pre_build:
    commands:
      - cd ./web/frontend; npm install;
  build:
    commands:
      - npm run build; npm run export; cd ../../;
  post_build:
    commands:
      - mv ./web/frontend/out ./frontend
      - mv ./web/backend ./backend
artifacts:
  secondary-artifacts:
    Frontend:
      files:
        - '**/*'
      base-directory: ./frontend
    Backend:
      files:
        - '**/*'
      base-directory: ./backend