# Generated by Django 4.0.5 on 2022-07-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userupload',
            table='uploads',
        ),
    ]
