# Generated by Django 4.0.5 on 2022-07-08 22:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vesta', '0002_alter_userupload_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.AddField(
            model_name='userupload',
            name='uploadtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('chatOn', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.authuser')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricerange', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('timerange', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.authuser')),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='ListingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=16)),
                ('duration', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('rate', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('utilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('unavailable', 'Unavailable')], default='available', max_length=15)),
                ('floorplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorplan_fk', to='vesta.userupload')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.authuser')),
                ('proof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_fk', to='vesta.userupload')),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.listingproperty')),
            ],
            options={
                'db_table': 'listing',
            },
        ),
    ]
