# Generated by Django 4.1.5 on 2023-01-21 18:38

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("vesta", "0002_change_country_to_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="listinglisting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="content",
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(), upload_to="uploads"
            ),
        ),
    ]
