# Generated by Django 4.0.5 on 2022-07-09 03:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import vesta.models


class Migration(migrations.Migration):

    dependencies = [
        ('vesta', '0003_listingproperty_userupload_uploadtime_usersettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', django.contrib.postgres.fields.ArrayField(base_field=vesta.models.MessageField(), size=None)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user1_fk', to='vesta.authuser')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user2_fk', to='vesta.authuser')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='MessagingBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_blocked_fk', to='vesta.authuser')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_blocker_fk', to='vesta.authuser')),
            ],
            options={
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='ListingInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('sold', 'Sold'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_fk', to='vesta.authuser')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.listinglisting')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_fk', to='vesta.authuser')),
            ],
            options={
                'db_table': 'interest',
            },
        ),
        migrations.CreateModel(
            name='ListingFlaggedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('Illegal', 'Illegal'), ('Unethical', 'Unethical'), ('Inappropriate', 'Inappropriate')], max_length=20, null=True)),
                ('flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.authuser')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesta.listinglisting')),
            ],
            options={
                'db_table': 'flagged_listing',
            },
        ),
    ]
