# Generated by Django 4.0.6 on 2022-07-13 18:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vesta', '0004_messagingchat_messagingblocks_listinginterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='listinglisting',
            name='duration',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listinglisting',
            name='floorplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floorplan_fk', to='vesta.userupload'),
        ),
        migrations.AlterField(
            model_name='listinglisting',
            name='proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_fk', to='vesta.userupload'),
        ),
        migrations.AlterField(
            model_name='listinglisting',
            name='rate',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listinglisting',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='listinglisting',
            name='utilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pricerange',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='timerange',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True),
        ),
    ]
