# Generated by Django 4.1.5 on 2023-02-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesta', '0004_remove_listinginterest_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listinglisting',
            index=models.Index(fields=['owner'], name='listing_owner_i_0c8e12_idx'),
        ),
        migrations.AddIndex(
            model_name='listinglisting',
            index=models.Index(fields=['status'], name='listing_status_f437b1_idx'),
        ),
    ]
