# Generated by Django 4.1.5 on 2023-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vesta", "0006_listinglisting_images"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listinginterest",
            constraint=models.UniqueConstraint(
                fields=("buyer", "listing"), name="user_can_bookmark_listing_only_once"
            ),
        ),
    ]
